---
substitutions:
  icon_play: "\uF000"
  icon_pause: "\uF001"
  icon_forward: "\uF002"
  icon_backward: "\uF003"
  icon_music: "\uF004"
  icon_volume: "\uF005"

external_components:
  - source: ./components
    components: [const, image, generic_image, media_source, sendspin]
    refresh: 0s
  

font:
  - file:
      family: DM+Sans
      weight: 300
      type: gfonts
    id: font_music_title
    size: 14
    bpp: 4
    glyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,!?-''_()"'

  - file: ./src/assets/fonts/media_player_icons.ttf
    id: media_player_icons
    size: 24
    bpp: 4
    glyphs:
    - ${icon_play}  # play-solid-full
    - ${icon_pause}  # pause-solid-full
    - ${icon_forward}  # forward-solid-full
    - ${icon_backward}  # backward-solid-full
    - ${icon_music}
    - ${icon_volume}

color:
  - id: col_music_bg
    hex: "000000"
  - id: col_music_ring_track
    hex: "000000"
  - id: col_music_ring_progress
    hex: "764CFF"
  - id: col_music_play_btn
    hex: "A98FFF"
  - id: col_music_dark
    hex: "1A1040"

image:
  - file: src/assets/images/place_holder.png
    id: place_holder
    type: RGB565
    transparency: alpha_channel
    resize: 108x108

sendspin:
  id: sendspin_hub

generic_image:
  - platform: sendspin
    id: sendspin_cover_art
    format: jpg
    type: rgb565
    resize: 108x108
    image_source: ALBUM
    on_image_decoded:
      - logger.log: "Album image decoded"
      - lambda: |-
          lv_obj_t *obj = id(img_music_cover);
          static lv_anim_t a;
          lv_anim_init(&a);
          lv_anim_set_var(&a, obj);
          lv_anim_set_values(&a, LV_OPA_COVER, LV_OPA_TRANSP);
          lv_anim_set_time(&a, 200);
          lv_anim_set_exec_cb(&a, [](void *var, int32_t v) {
            lv_obj_set_style_opa((lv_obj_t *)var, v, 0);
          });
          lv_anim_start(&a);
      - delay: 200ms    
      - lvgl.image.update:
          id: img_music_cover
          src: sendspin_cover_art
      - lambda: |-
          lv_obj_t *obj = id(img_music_cover);
          static lv_anim_t a;
          lv_anim_init(&a);
          lv_anim_set_var(&a, obj);
          lv_anim_set_values(&a, LV_OPA_TRANSP, LV_OPA_COVER);
          lv_anim_set_time(&a, 300);
          lv_anim_set_exec_cb(&a, [](void *var, int32_t v) {
            lv_obj_set_style_opa((lv_obj_t *)var, v, 0);
          });
          lv_anim_start(&a);

text_sensor:
  - platform: sendspin
    id: track_title
    type: title
    on_value:
      - lambda: |-
          if ( !x.empty() ) 
            lv_label_set_text(id(lbl_music_title), x.c_str());
          else
            lv_label_set_text(id(lbl_music_title), "Ready to Play");

  - platform: sendspin
    id: track_artist
    type: artist
    
  - platform: homeassistant
    id: media_player_status
    entity_id: media_player.m5stack_dial
    on_value:
      - lambda: |-
          ESP_LOGD("Media Player", "Read media player status: %s", x.c_str());
          if ( x == "idle" || x == "paused" 
              || x == "unavailable" || x == "off"
              || x == "unknown" )
          {
            id(music_playing) = false;
            lv_label_set_text(id(play_label), "${icon_play}");
          }
          else if ( x == "playing" ) {
            id(music_playing) = true;
            lv_label_set_text(id(play_label), "${icon_pause}");
          }
          // read track progress and duration when state change
          id(local_progress_ms) = id(sendspin_hub).get_track_progress_ms();
          id(local_duration_ms) = id(sendspin_hub).get_track_duration_ms();

globals:
  - id: in_music
    type: bool
    initial_value: 'false'
  - id: music_volume
    type: int
    initial_value: '36'
  - id: music_playing
    type: bool
    initial_value: 'false'
  - id: music_progress
    type: int
    initial_value: '0'
  - id: local_progress_ms
    type: int
    restore_value: false
    initial_value: '0'
  - id: local_duration_ms
    type: int
    restore_value: false
    initial_value: '0'

script:
  - id: open_music
    then:
      - globals.set: {id: in_music, value: 'true'}
      - globals.set: {id: in_menu, value: 'false'}
      - script.execute: refresh_music_volume
      - lvgl.page.show:
          id: page_music
          animation: MOVE_LEFT

  - id: close_music
    then:
      - globals.set: {id: in_music, value: 'false'}
      - lvgl.page.show:
          id: page_clock
          animation: MOVE_RIGHT

  - id: play_next
    then:
      - homeassistant.action:
          action: media_player.media_next_track
          data:
            entity_id: media_player.m5stack_dial

  - id: play_prev
    then:
      - homeassistant.action:
          action: media_player.media_previous_track
          data:
            entity_id: media_player.m5stack_dial
  - id: play_toggle
    then:
      - lambda: |-
          id(music_playing) = !id(music_playing);
      - homeassistant.action:
          action: media_player.media_play_pause
          data:
            entity_id: media_player.m5stack_dial
      - lvgl.label.update:
          id: play_label
          text: ${icon_pause}
  - id: music_volume_up
    then:
      - lambda: |-
          int v = id(music_volume) + 14;
          if (v > 100) v = 100;
          id(music_volume) = v;    
      - homeassistant.action:
          action: media_player.volume_up
          data:
            entity_id: media_player.m5stack_dial
      - script.execute: refresh_music_volume     

  - id: music_volume_down
    then:
      - lambda: |-
          int v = id(music_volume) - 14;
          if (v < 0) v = 0;
          id(music_volume) = v;
      - homeassistant.action:
          action: media_player.volume_down
          data:
            entity_id: media_player.m5stack_dial
      - script.execute: refresh_music_volume

  - id: refresh_music_volume
    then:
      - lambda: |-
          int v = id(music_volume);
          auto off = lv_color_hex(0x000000);
          lv_obj_set_style_bg_color(id(vol_bar_1), v >  0 ? lv_color_hex(0xA98FFF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_2), v > 14 ? lv_color_hex(0xA387FF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_3), v > 28 ? lv_color_hex(0x9D7FFF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_4), v > 42 ? lv_color_hex(0x9170FF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_5), v > 57 ? lv_color_hex(0x8661FF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_6), v > 71 ? lv_color_hex(0x7E57FF) : off, 0);
          lv_obj_set_style_bg_color(id(vol_bar_7), v > 85 ? lv_color_hex(0x764CFF) : off, 0);
          ESP_LOGI("music", "volume=%d", v);

  - id: refresh_music_progress
    then:
      - lambda: |-
          lv_arc_set_value(id(arc_music_progress), id(music_progress));
          ESP_LOGD("music", "progress=%d", id(music_progress));

lvgl:
  pages:
    - id: page_music
      bg_color: col_music_bg
      bg_opa: COVER
      scrollbar_mode: "OFF"
      widgets:
        - obj:
            align: TOP_LEFT
            x: 0
            y: 0
            width: 240
            height: 240
            radius: 120
            clip_corner: true
            bg_color: col_music_bg
            bg_opa: COVER
            border_width: 0
            pad_all: 0
            scrollbar_mode: "OFF"
            widgets:
              - arc:
                  id: arc_music_progress
                  align: CENTER
                  width: 232
                  height: 232
                  rotation: 270
                  start_angle: 0
                  end_angle: 360
                  min_value: 0
                  max_value: 100
                  value: 0
                  arc_color: col_music_ring_track
                  arc_width: 5
                  arc_opa: COVER
                  arc_rounded: true
                  adjustable: false
                  clickable: false
                  indicator:
                    arc_color: col_music_ring_progress
                    arc_width: 5
                    arc_opa: COVER
                    arc_rounded: true
                  knob:
                    bg_opa: TRANSP
                    border_width: 0
                    width: 0
                    height: 0

              - obj:
                  x: 60
                  y: 12
                  width: 120
                  height: 120
                  radius: 60
                  bg_opa: TRANSP
                  border_width: 0
                  clip_corner: true
                  clickable: false
                  scrollbar_mode: "OFF"
                  widgets:
                    - image:
                        id: img_music_cover
                        src: place_holder
                        x: 0
                        y: 0
              - label:
                  id: lbl_music_title
                  x: 20
                  y: 134
                  width: 200
                  text: "Ready to Play"
                  text_font: font_music_title
                  text_color: 0xFFFFFF
                  text_align: CENTER
                  on_boot:
                    - lambda: |-
                        lv_obj_set_style_anim_time(id(lbl_music_title), 15000, 0);
                        lv_label_set_long_mode(id(lbl_music_title), LV_LABEL_LONG_SCROLL);
                        lv_label_set_recolor(id(lbl_music_title), true);
              - label:
                  text_font: media_player_icons
                  text: ${icon_volume}
                  x: 70
                  y: 150
                  text_color: 0xFFFFFF

              - obj: {id: vol_bar_1, x: 97,  y: 155, width: 6, height: 12, radius: 3, bg_color: 0xA98FFF, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_2, x: 107, y: 155, width: 6, height: 12, radius: 3, bg_color: 0xA387FF, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_3, x: 117, y: 155, width: 6, height: 12, radius: 3, bg_color: 0x000000, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_4, x: 127, y: 155, width: 6, height: 12, radius: 3, bg_color: 0x000000, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_5, x: 137, y: 155, width: 6, height: 12, radius: 3, bg_color: 0x000000, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_6, x: 147, y: 155, width: 6, height: 12, radius: 3, bg_color: 0x000000, bg_opa: COVER, border_width: 0, clickable: false}
              - obj: {id: vol_bar_7, x: 157, y: 155, width: 6, height: 12, radius: 3, bg_color: 0x000000, bg_opa: COVER, border_width: 0, clickable: false}

              - button:
                  x: 62
                  y: 184
                  width: 24
                  height: 24
                  bg_color: col_music_dark
                  bg_opa: TRANSP
                  shadow_opa: TRANSP
                  border_width: 0
                  scrollbar_mode: "OFF"
                  id: prev_btn
                  on_press:
                    - script.execute: play_prev
                  on_boot:
                    - lambda: |-
                        lv_group_remove_obj(id(prev_btn));
                  widgets:
                    - label:
                        text_font: media_player_icons
                        text: ${icon_backward}
                        text_color: 0xFFFFFF
                        align: CENTER

              - button:
                  x: 102
                  y: 175
                  id: play_btn
                  width: 44
                  height: 44
                  radius: 22
                  bg_color: col_music_play_btn
                  bg_opa: COVER
                  shadow_opa: TRANSP
                  border_width: 0
                  scrollbar_mode: "OFF"
                  on_press:
                    - script.execute: play_toggle
                  on_boot:
                    - lambda: |-
                        lv_group_remove_obj(id(play_btn));
                  widgets:
                    - label:
                        id: play_label
                        text_font: media_player_icons
                        text: ${icon_play}
                        text_color: 0xFFFFFF
                        align: CENTER

              - button:
                  id: next_btn
                  x: 161
                  y: 184
                  width: 24
                  height: 24
                  bg_color: col_music_dark
                  bg_opa: TRANSP
                  shadow_opa: TRANSP
                  border_width: 0
                  scrollbar_mode: "OFF"
                  on_press:
                    - script.execute: play_next
                  on_boot:
                    - lambda: |-
                        lv_group_remove_obj(next_btn);
                  widgets:
                    - label:
                        text_font: media_player_icons
                        text: ${icon_forward}
                        text_color: 0xFFFFFF
                        align: CENTER

interval:
  - interval: 200ms
    then:
      - lambda: |-
          if (!id(music_playing)) return;
          auto dur = id(local_duration_ms);
          if (dur == 0) return;
          id(local_progress_ms) += 200;

          auto local_val = id(local_progress_ms);
          
          if ( id(media_player_status).state == "idle" 
               || id(media_player_status).state == "paused"
               || id(media_player_status).state == "playing"
               || id(media_player_status).state == "buffering" ) {
            auto sync_val = id(sendspin_hub).get_track_progress_ms();
            if ( sync_val != local_val ) {
              id(local_progress_ms) = sync_val;
            }
          }

          if (id(local_progress_ms) > dur) id(local_progress_ms) = dur;
          float progress = (float)id(local_progress_ms) / dur * 100.0f;
          if (progress > 100) progress = 100;
          lv_arc_set_value(id(arc_music_progress), (int)progress);